language: node_js
node_js:
- stable
script:
 - npm run coverage
branches:
   only:
   - development2
notifications:
    email:
      recipients:
        - matthoing@icloud.com
        on_success: never 
        on_failure: always  